services:
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr:latest
    ports:
      - 8787:8787
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Phoenix
    volumes:
      - ./config:/config
      - /mnt/data:data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - media
networks:
  media:
    external: true
